Models/AthleteModel.cs
using System.Collections.Generic;

namespace Olympics.Models
{
    public class AthleteModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int CountryId { get; set; }

        public string CountryName { get; set; }
        public string SportsName { get; set; }
        public bool TeamActivity { get; set; }
        public List<string> Sports { get; set; } = new List<string>();

    }
}

Models/CountryModel.cs
namespace Olympics.Models
{
    public class CountryModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ISO3 { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Olympics.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FilterSortModel.cs
using System.Collections.Generic;

namespace Olympics.Models
{
    public class FilterSortModel
    {
        public string FilterCountry { get; set; }
        public string FilterSport { get; set; }
        public string FilterActivity { get; set; }
        public string SortOrder { get; set; }
        public List<string> SortProperties { get; set; } = new() { "Name", "Surname", "Country" };
        public List<string> TeamActivityProperties { get; set; } = new List<string>() { "Team", "Non-team" };

    }
}

Models/GeneralModel.cs
using System.Collections.Generic;

namespace Olympics.Models
{
    public class GeneralModel
    {
        public AthleteModel Athlete { get; set; }
        public List<AthleteModel> Athletes { get; set; } = new List<AthleteModel>();
        public List<CountryModel> Countries { get; set; } = new List<CountryModel>();
        public List<SportsModel> Sports { get; set; } = new List<SportsModel>();
        public FilterSortModel FilterSort { get; set; } = new FilterSortModel();
    }
}

Models/SportsModel.cs
using System.Collections.Generic;

namespace Olympics.Models
{
    public class SportsModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TeamActivity { get; set; }
        public List<string> TeamActivityProperties { get; set; } = new List<string>() { "Team", "Non-team" };
    }
}

Models/ViewsGeneralModel.cs
using System;
using System.Collections.Generic;

namespace Olympics.Models
{
    public class ViewsGeneralModel
    {
        public AthleteModel Athlete { get; set; }
        public List<AthleteModel> Athletes { get; set; } = new List<AthleteModel>();
        public List<CountryModel> Countries { get; set; } = new List<CountryModel>();
        public List<SportsModel> Sports { get; set; } = new List<SportsModel>();
        public FilterSortModel FilterSort { get; set; } = new FilterSortModel();
    }
}

Controllers/AthleteController.cs
using Microsoft.AspNetCore.Mvc;
using Olympics.Models;
using Olympics.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Olympics.Controllers
{
    public class AthleteController : Controller
    {
        private readonly AthleteDBService _athleteDBService;
        private readonly GeneralDBService _generalDBService;

        public AthleteController(AthleteDBService athleteDBService, GeneralDBService viewsGeneralService)
        {
            _athleteDBService = athleteDBService;
            _generalDBService = viewsGeneralService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            GeneralModel data = _generalDBService.GetGeneralDBData();
            return View(data);
        }

        public IActionResult Submit(GeneralModel model)
        {
            _athleteDBService.Create(model);
            GeneralModel data = _generalDBService.GetGeneralDBData();
            data.Athletes = _athleteDBService.Read();
            return View("Index", data);
        }

        public IActionResult Create()
        {
            GeneralModel data = _generalDBService.GetGeneralDBData();
            return View(data);
        }

        [HttpPost]
        public IActionResult FilterGeneral(GeneralModel model)
        {
            GeneralModel data = _generalDBService.GetGeneralDBData();
            data.Athletes = _athleteDBService.FilterGeneral(model);
            return View("Index", data);
        }

        [HttpPost]
        public IActionResult SortBy(GeneralModel model)
        {
            GeneralModel data = _generalDBService.GetGeneralDBData();
            data.Athletes = _athleteDBService.SortBy(model);
            return View("Index", data);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            GeneralModel data = _generalDBService.GetGeneralDBData();
            data.Athletes = _athleteDBService.Delete(id);
            return View("Index", data);
        }

        // GET: Animal/Edit/5
        public ActionResult Edit(int id)
        {
            GeneralModel data = _generalDBService.GetGeneralDBData();
            data.Athletes = _athleteDBService.Edit(id);
            return View("Index", data);
        }
    }
}

Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Olympics.Models;
using Olympics.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Olympics.Controllers
{
    public class CountryController : Controller
    {
        private readonly CountryDBService _countryDBService;

        public CountryController(CountryDBService countryDBService)
        {
            _countryDBService = countryDBService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<CountryModel> data = _countryDBService.Read();
            return View(data);
        }

        public IActionResult Submit(CountryModel model)
        {
            _countryDBService.Create(model);
            List<CountryModel> data = _countryDBService.Read();
            return View("Index", data);
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Olympics.Models;

namespace Olympics.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Olympics.Models;
using Olympics.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Olympics.Controllers
{
    public class SportsController : Controller
    {
        private readonly SportsDBService _sportsDBService;

        public SportsController(SportsDBService sportsDBService)
        {
            _sportsDBService = sportsDBService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            List<SportsModel> data = _sportsDBService.Read();
            return View(data);
        }

        public IActionResult Submit(SportsModel model)
        {
            _sportsDBService.Create(model);
            List<SportsModel> data = _sportsDBService.Read();
            return View("Index", data);
        }

        public IActionResult Create()
        {
            return View();
        }
    }
}

Views/Athlete/Create.cshtml
@model GeneralModel

<h5>Create new athlete</h5>

@using (Html.BeginForm("Submit", "Athlete", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.LabelFor(x => x.Athlete.Name)
            @Html.TextBoxFor(x => x.Athlete.Name)
            @Html.LabelFor(x => x.Athlete.Surname)
            @Html.TextBoxFor(x => x.Athlete.Surname)
            @Html.DropDownListFor(x => x.Countries[0].Name, new SelectList(Model.Countries, "Name", "Name"))
            @Html.DropDownListFor(x => x.Sports[0].Name, new SelectList(Model.Sports, "Name", "Name"))
            <input type="submit" value="Submit" />
        </div>
    </div>
}

@Html.ValidationSummary()

Views/Athlete/Edit.cshtml
@model GeneralModel

<h5>Create new athlete</h5>

@using (Html.BeginForm("Submit", "Athlete", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.LabelFor(x => x.Athlete.Name)
            @Html.TextBoxFor(x => x.Athlete.Name)
            @Html.LabelFor(x => x.Athlete.Surname)
            @Html.TextBoxFor(x => x.Athlete.Surname)
            @Html.DropDownListFor(x => x.Countries[0].Name, new SelectList(Model.Countries, "Name", "Name"))
            @Html.DropDownListFor(x => x.Sports[0].Name, new SelectList(Model.Sports, "Name", "Name"))
            <input type="submit" value="Submit" />
        </div>
    </div>
}

@Html.ValidationSummary()

Views/Athlete/Index.cshtml
@model GeneralModel

<h3>Athletes</h3>

@using (Html.BeginForm("FilterGeneral", "Athlete", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.DropDownListFor(x => Model.FilterSort.FilterSport, new SelectList(Model.Sports, "Name", "Name"))
            @Html.DropDownListFor(x => Model.FilterSort.FilterCountry, new SelectList(Model.Countries, "Name", "Name"))
            @Html.DropDownListFor(x => Model.FilterSort.FilterActivity, new SelectList(Model.FilterSort.TeamActivityProperties))
            <input type="submit" value="Filter" />
        </div>
    </div>
}

@using (Html.BeginForm("SortBy", "Athlete", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.DropDownListFor(x => Model.FilterSort.SortOrder, new SelectList(Model.FilterSort.SortProperties))
            <input type="submit" value="Sort" />
        </div>
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">Country</th>
            <th scope="col">Sports</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Athletes)
        {
        <tr>
            <td>@item.Name</td>
            <td>@item.Surname</td>
            <td>@item.CountryName</td>
            <td>
                @foreach (var sports in item.Sports)
                {
                    <ul>@sports</ul>
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @using (Html.BeginForm("Delete", "Athlete", new { id = $"{item.Id}" }, FormMethod.Post))
                {
                    <div class="container-full" style="background-color:aliceblue">
                        <div class="container">

                            <input type="submit" value="Delete" />
                        </div>
                    </div>
                }
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Country/Create.cshtml
@model CountryModel

<h5>Create new country</h5>

@using (Html.BeginForm("Submit", "Country", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name)
            @Html.LabelFor(x => x.ISO3)
            @Html.TextBoxFor(x => x.ISO3)
            <input type="submit" value="Submit" />
        </div>
    </div>
}

@Html.ValidationSummary()

Views/Country/Index.cshtml
@model List<CountryModel>

<h3>Countries</h3>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">ISO3</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.ISO3</td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Olympics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Olympics</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Create
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" asp-area="" asp-controller="Athlete" asp-action="Create">Create Athlete</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Sports" asp-action="Create">Create Sport</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Country" asp-action="Create">Create Country</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Athlete" asp-action="Index">Athletes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sports" asp-action="Index">Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Olympics - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Sports/Create.cshtml
@model SportsModel

<h5>Create new sport</h5>

@using (Html.BeginForm("Submit", "Sports", FormMethod.Post))
{
    <div class="container-full" style="background-color:aliceblue">
        <div class="container">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name)
            @Html.LabelFor(x => x.TeamActivity)
            @Html.TextBoxFor(x => x.TeamActivity)
            <input type="submit" value="Submit" />
        </div>
    </div>
}

@Html.ValidationSummary()

Views/Sports/Index.cshtml
@model List<SportsModel>

<h3>Sports</h3>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">TeamActivity</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.TeamActivity</td>
            </tr>
        }
    </tbody>
</table>